
modLoader = "javafml"

loaderVersion = "${loader_version_range}"

license = "${mod_license}"

[[mods]]
modId = "${mod_id}"

version = "${mod_version}"

displayName = "${mod_name}"

authors = "NetPDR"

description = '''A mod that makes players to use Herobrine's obsidian from Minecraft Animation AnnoyingVillager'''

[[dependencies."${mod_id}"]] #optional

modId = "forge"

mandatory = true

versionRange = "${forge_version_range}"

ordering = "NONE"

side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true

versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
